version: "3"
services:

  client:
    runtime: nvidia
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/client
      - ../../federated/forcast_federated_learning:/client/forcast_federated_learning
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    env_file:
      - ./.env
    deploy:
      replicas: ${NUM_CLIENTS}
    network_mode: host
    stdin_open: true
    tty: true