version: "3"
services:

  client:
    runtime: nvidia
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/client
      - ../../federated/forcast_federated_learning:/client/forcast_federated_learning
    network_mode: host
    stdin_open: true
    tty: true